apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nlb69u1ag-go
  janus-idp.io/tekton: nlb69u1ag-go
  backstage.io/kubernetes-id: nlb69u1ag-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nlb69u1ag-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
